services:
  - type: web
    name: my-app
    runtime: node
    buildCommand: npm install && npx expo export --platform web && npm run server:build
    startCommand: npm run server:prod
    envVars:
      - key: NODE_ENV
        value: production
